services:
  web:
    build:
      context: ./web
      dockerfile: ./docker/local.Dockerfile
    volumes:
      - ./web/src:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file: ./environments/local.env
    command: ["npm", "run", "devstart"]
  
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - mysql
    env_file: ./environments/local.env
    ports:
      - 3003:3000
    volumes:
      - ./api/src:/app
      - /app/node_modules
    command: ["npm", "run", "devstart"]
  
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    env_file: ./environments/local.env
    volumes:
      - ../import-data:/data
      - ./mysql-data:/var/lib/mysql
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql


